
find_path( ORBSLAM2_INCLUDE_DIRS ORB_SLAM2/System.h
    HINTS
        # ${CMAKE_INSTALL_PREFIX}/include
        ${GLOBAL_INCLUDE_ROOT}
)
find_library( ORBSLAM2_LIBS ORB_SLAM2
    HINTS
        # ${CMAKE_INSTALL_PREFIX}/lib
        ${GLOBAL_LIB_ROOT}
)

set( ORBSLAM2_FOUND FALSE )

if( ORBSLAM2_INCLUDE_DIRS AND ORBSLAM2_LIBS )
    set( ORBSLAM2_FOUND TRUE )
endif( ORBSLAM2_INCLUDE_DIRS AND ORBSLAM2_LIBS )
